### POST
POST    http://localhost:3000/api/auth/register
content-type: application/json

{
    "username":"ferasbbm",
    "password":"password",
    "email":"feras.bbm@gmail.com"
}   

### Login Request
POST   http://localhost:3000/api/auth/login
content-type: application/json

{
    "username":"ferasbbm",
    "password":"password"
}   

### Logout Request
POST   http://localhost:3000/api/auth/logout
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMxLCJ1c2VybmFtZSI6ImZlcmFzYmJtIiwiaWF0IjoxNzM4ODM5MzQ5LCJleHAiOjE3Mzg4NDI5NDl9.Uqm0AwaWCq2UP8niL1zs7cXWWTsgAEKypU_CFaDRWPg

