### POST
POST    http://localhost:3000/api/auth/register
content-type: application/json

{
    "username":"ferasbbm",
    "password":"password",
    "email":"feras.bbm@gmail.com"
}   

### Login Request
POST   http://localhost:3000/api/auth/login
content-type: application/json

{
    "username":"ferasbbm",
    "password":"password"
}   

### Profile Request
POST   http://localhost:3000/api/auth/logout
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMwLCJ1c2VybmFtZSI6ImZlcmFzYmJtIiwiaWF0IjoxNzM4NzYwNTk4LCJleHAiOjE3Mzg3NjQxOTh9.TLcXF54Dn5vhOpPKhy8S9HAj-5fpyWyt47JtBYKlyaY

