### POST
POST   http://localhost:3000/api/users/auth/register
content-type: application/json

{
    "username":"ferasbbm",
    "password":"password",
    "email":"feras.bbm@gmail.com"
}   

### Login Request
POST   http://localhost:3000/api/users/auth/login
content-type: application/json

{
    "username":"ferasbbm",
    "password":"password"
}   