### POST  create new  link
POST   http://localhost:3000/api/link-shortening
content-type: application/json

{
    "originalURL": "https://www.example.com"
}

### GET
GET   http://localhost:3000/api/link-shortening/1
content-type: application/json
