############## POST  create new link ##############

POST   http://localhost:3000/api/link-shortening
content-type: application/json

{
    "originalURL": "https://www.example.com"
}

############## GET ##############
GET   http://localhost:3000/api/link-shortening/11
content-type: application/json


############## PUT  update existing link ##############
PATCH    http://localhost:3000/api/link-shortening/11
content-type: application/json

{
    "originalURL": "https://www.10101.com"
}

############## DELETE delete link using id  ##############
DELETE    http://localhost:3000/api/link-shortening/11
content-type: application/json
