### User Profile Request
GET   http://localhost:3000/api/users/profile
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEyLCJ1c2VybmFtZSI6ImZlcmFzYmJtIiwiaWF0IjoxNzM5MzUwMzIzLCJleHAiOjE3MzkzNTA5MjN9.e1fCHagcaC5C0vRA0Km2iDL2VtjN3HWakZTei_w7f3I